FROM silintl/php7
COPY docker/config.conf /etc/apache2/sites-enabled/

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install nodejs npm -y
RUN cp /usr/bin/nodejs /usr/bin/node
COPY . /app
RUN composer install

WORKDIR /app/web
RUN npm install
RUN npm install --only=dev
RUN npm install -g grunt
RUN grunt

WORKDIR /app


EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
