FROM silintl/php7
COPY docker/config.conf /etc/apache2/sites-enabled/

RUN mkdir -p /app
WORKDIR /app

RUN apt-get update && apt-get install nodejs npm -y
RUN cp /usr/bin/nodejs /usr/bin/node

WORKDIR /app/public
RUN npm install
RUN npm run build

WORKDIR /app

EXPOSE 80
CMD ["apache2ctl", "-D", "FOREGROUND"]
